const cities = [
  { id: "805", title: "An Giang" },
  { id: "717", title: "Bà Rịa - Vũng Tàu" },
  { id: "711", title: "Bình Dương" },
  { id: "707", title: "Bình Phước" },
  { id: "715", title: "Bình Thuận" },
  { id: "507", title: "Bình Định" },
  { id: "821", title: "Bạc Liêu" },
  { id: "207", title: "Bắc Cạn" },
  { id: "221", title: "Bắc Giang" },
  { id: "223", title: "Bắc Ninh" },
  { id: "811", title: "Bến Tre" },
  { id: "203", title: "Cao Bằng" },
  { id: "823", title: "Cà Mau" },
  { id: "815", title: "Cần Thơ" },
  { id: "603", title: "Gia Lai" },
  { id: "201", title: "Hà Giang" },
  { id: "111", title: "Hà Nam" },
  { id: "101", title: "Hà Nội" },
  { id: "405", title: "Hà Tĩnh" },
  { id: "305", title: "Hòa Bình" },
  { id: "109", title: "Hưng Yên" },
  { id: "107", title: "Hải Dương" },
  { id: "103", title: "Hải Phòng" },
  { id: "816", title: "Hậu Giang" },
  { id: "511", title: "Khánh Hòa" },
  { id: "813", title: "Kiên Giang" },
  { id: "601", title: "Kon Tum" },
  { id: "302", title: "Lai Châu" },
  { id: "801", title: "Long An" },
  { id: "205", title: "Lào Cai" },
  { id: "703", title: "Lâm Đồng" },
  { id: "209", title: "Lạng Sơn" },
  { id: "113", title: "Nam Định" },
  { id: "403", title: "Nghệ An" },
  { id: "117", title: "Ninh Bình" },
  { id: "705", title: "Ninh Thuận" },
  { id: "217", title: "Phú Thọ" },
  { id: "509", title: "Phú Yên" },
  { id: "407", title: "Quảng Bình" },
  { id: "503", title: "Quảng Nam" },
  { id: "505", title: "Quảng Ngãi" },
  { id: "225", title: "Quảng Ninh" },
  { id: "409", title: "Quảng Trị" },
  { id: "819", title: "Sóc Trăng" },
  { id: "303", title: "Sơn La" },
  { id: "701", title: "TP Hồ Chí Minh" },
  { id: "401", title: "Thanh Hoá" },
  { id: "115", title: "Thái Bình" },
  { id: "215", title: "Thái Nguyên" },
  { id: "411", title: "Thừa Thiên - Huế" },
  { id: "807", title: "Tiền Giang" },
  { id: "817", title: "Trà Vinh" },
  { id: "211", title: "Tuyên Quang" },
  { id: "709", title: "Tây Ninh" },
  { id: "809", title: "Vĩnh Long" },
  { id: "219", title: "Vĩnh Phúc" },
  { id: "213", title: "Yên Bái" },
  { id: "301", title: "Điện Biên" },
  { id: "501", title: "Đà Nẵng" },
  { id: "605", title: "Đắc Lắc" },
  { id: "606", title: "Đắk Nông" },
  { id: "713", title: "Đồng Nai" },
  { id: "803", title: "Đồng Tháp" }
];

module.exports = cities;
